### ISSUE TITLE
Glassfish orb doesn't work with java 15

### ISSUE THREAD

**Issue by WriteWithPaint** [javaee/glassfish-corba#36]
My corba code runs find with glassfish 4.2.2 and java 11.  However, it won't run with Java 15.  I get the following error

Exception in thread "main" java.lang.UnsupportedOperationException: WARNING: GMBALTLIB00004: Multiple upper bounds not supported on S
	at com.sun.proxy.$Proxy35.multipleUpperBoundsNotSupported(Unknown Source)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.lookup(TypeEvaluator.java:631)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitTypeVariable(TypeEvaluator.java:573)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:397)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:552)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$1.evaluate(TypeEvaluator.java:537)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$1.evaluate(TypeEvaluator.java:535)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:533)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:716)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:712)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:70)
	at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:93)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.processClass(TypeEvaluator.java:710)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.getCorrectDeclaration(TypeEvaluator.java:668)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitClassDeclaration(TypeEvaluator.java:445)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:391)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:552)
	at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.access$600(TypeEvaluator.java:372)
(etc)

when I call Orb.init()

**Comment by edbratt** [comment]
Is it possible you are referring to glassfish-corba-orb version? As far as I know, there was never a GlassFish 4.2.2 release. After GlassFish 5.0 was finished, all of Java EE (including GlassFish and it's associated components that Oracle was responsible for) was contributed to Eclipse Foundation.
 
GlassFish corba orb 4.2.2 was released as part of Eclipse GlassFish 6 under the Jakarta EE project ([here](https://github.com/eclipse-ee4j/orb/releases/tag/4.2.2-RELEASE)).

Newer releases of GlassFish 6 support newer versions of Java. If possible, I would recommend you first try upgrading to the latest Eclipse GlassFish 6 release. If that fails to resolve your issue, you are welcome to file this issue in the Eclipse GlassFish [corba-orb project](https://github.com/eclipse-ee4j/orb/issues).

If I've misunderstood your issue, you are welcome to add more details and reopen this issue.
